# Generated by Selenium IDE

import time
from selenium import webdriver
import json
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support.wait import WebDriverWait


class TestVHNC():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 10000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def test_vHNC(self):
        self.driver.get("https://mbaas.desa.co.davivienda.com/lpa/")
        self.driver.maximize_window()
        self.driver.delete_all_cookies()
        self.driver.find_element(By.XPATH, "//input[@placeholder=\'Usuario\']").send_keys("")
        self.driver.find_element(By.XPATH, "//input[@placeholder=\'Contraseña\']").send_keys("")
        self.driver.find_element(By.XPATH, "//button[normalize-space()=\'ACEPTAR\']").click()
        select = Select(WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR,
                                                                                         ".formGroup__input.formGroup__input--selectMembresia.ng-untouched.ng-pristine.ng-invalid"))))
        select.select_by_index(11)
        select = Select(WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR,
                                                                                         ".formGroup__input.formGroup__input--selectMembresia.ng-untouched.ng-pristine.ng-valid"))))
        select.select_by_index(5)
        self.driver.find_element(By.XPATH, "//input[@type=\'text\'][1]").send_keys("1")
        self.driver.find_element(By.CSS_SELECTOR, ".ng-untouched:nth-child(3)").send_keys("")
        self.vars["root"] = self.driver.current_window_handle
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.CSS_SELECTOR, ".aceptar").click()
        self.vars["userAgreement"] = self.wait_for_window(20000)
        self.driver.switch_to.window(self.vars["userAgreement"])
        self.driver.switch_to.window(self.vars["root"])
        self.driver.close()
        self.driver.switch_to.window(self.vars["userAgreement"])
        WebDriverWait(self.driver, 12).until(EC.element_to_be_clickable((By.XPATH, "//div[@class='dav-buttonContainer"
                                                                                   "--vertical']//button["
                                                                                   "@name='button'][normalize-space("
                                                                                   ")='Continuar']"))).click()
        time.sleep(3)
        WebDriverWait(self.driver, 12).until(
            EC.element_to_be_clickable((By.XPATH, "(//input[@id='idNumber'])"))).send_keys("")
        WebDriverWait(self.driver, 12).until(
            EC.element_to_be_clickable((By.XPATH, "//button[@id='nextButton']"))).click()
        element = self.driver.find_element(By.ID, "nextButton")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        time.sleep(4)
        WebDriverWait(self.driver, 40).until(
            EC.element_to_be_clickable((By.XPATH, "//div[@class='checkbox__indicator']"))).click()
        WebDriverWait(self.driver, 26).until(EC.element_to_be_clickable((By.ID, "nextButton"))).click()
        WebDriverWait(self.driver, 25).until(
            EC.element_to_be_clickable((By.XPATH, "//input[@placeholder=\'$0,00\']"))).send_keys("")
        WebDriverWait(self.driver, 25).until(
            EC.element_to_be_clickable((By.XPATH, "//input[@id=\'plazo\']"))).send_keys("24")
        WebDriverWait(self.driver, 25).until(EC.element_to_be_clickable((By.XPATH, "//button[normalize-space("
                                                                                   ")='Simular']"))).click()
        time.sleep(10)
        WebDriverWait(self.driver, 25).until(EC.element_to_be_clickable((By.XPATH, "//button[@class='dav-button"
                                                                                   "--primary']"))).click()
        time.sleep(4)
        WebDriverWait(self.driver, 25).until(
            EC.element_to_be_clickable((By.XPATH, "//input[@id=\'correo\']"))).send_keys("")
        WebDriverWait(self.driver, 25).until(
            EC.element_to_be_clickable((By.XPATH, "//input[@id=\'celular\']"))).send_keys("")
        WebDriverWait(self.driver, 26).until(EC.element_to_be_clickable((((By.XPATH, "//span[normalize-space("
                                                                                     ")='Continuar']"))))).click()
        time.sleep(2)
        WebDriverWait(self.driver, 25).until(
            EC.element_to_be_clickable((By.XPATH, "//strong[normalize-space()='L']"))).click()
        otp = WebDriverWait(self.driver, 25).until(EC.visibility_of_element_located((By.XPATH, "//p[contains(text(),"
                                                                                               "'otp')]"))).get_attribute(
            "innerHTML")
        print(otp)
        otpnumber = otp[13] + otp[14] + otp[15] + otp[16] + otp[17] + otp[18] + otp[19] + otp[20]
        print(otpnumber)
        WebDriverWait(self.driver, 25).until(
            EC.element_to_be_clickable((By.XPATH, "//input[@id=\'inputotp\']"))).send_keys(otpnumber)
        WebDriverWait(self.driver, 26).until(EC.element_to_be_clickable((((By.XPATH, "//span[normalize-space("
                                                                                     ")='Continuar']"))))).click()
        WebDriverWait(self.driver, 25).until(
            EC.element_to_be_clickable((By.XPATH, "//input[@id=\'primerApellido\']"))).send_keys('')
        WebDriverWait(self.driver, 25).until(
            EC.element_to_be_clickable((By.XPATH, "//input[@id=\'segundoApellido\']"))).send_keys('')
        WebDriverWait(self.driver, 25).until(
            EC.element_to_be_clickable((By.XPATH, "//input[@id=\'nombreCompleto\']"))).send_keys('')
        WebDriverWait(self.driver, 25).until(
            EC.element_to_be_clickable((By.XPATH, "//input[@name=\'davDateTextField\']"))).send_keys('')
        self.driver.execute_script("window.scrollTo(0, window.innerHeight);")
        time.sleep(0.5)
        WebDriverWait(self.driver, 25).until(
            EC.element_to_be_clickable((By.XPATH, "//div[@name='davDropdown']"))).click()
        WebDriverWait(self.driver, 25).until(
            EC.element_to_be_clickable((By.XPATH, "//p[normalize-space()='Empleado/a']"))).click()
        WebDriverWait(self.driver, 25).until(
            EC.element_to_be_clickable((By.XPATH, "//input[@id=\'empresa\']"))).send_keys('')
        WebDriverWait(self.driver, 25).until(
            EC.element_to_be_clickable((By.XPATH, "//div[@id='tipoContrato']"))).click()
        WebDriverWait(self.driver, 25).until(
            EC.element_to_be_clickable((By.XPATH, "//p[normalize-space()='Prestación de servicios']"))).click()
        self.driver.execute_script("window.scrollTo(0, window.innerHeight);")
        time.sleep(0.5)
        WebDriverWait(self.driver, 25).until(
            EC.element_to_be_clickable((By.XPATH, "//input[@placeholder='$0,00']"))).send_keys('')
        WebDriverWait(self.driver, 25).until(
            EC.element_to_be_clickable((By.XPATH, "//div[@id='regimenSalud']"))).click()
        WebDriverWait(self.driver, 25).until(
            EC.element_to_be_clickable((By.XPATH, "//p[normalize-space()='Beneficiario']"))).click()
        WebDriverWait(self.driver, 25).until(
            EC.element_to_be_clickable((By.XPATH, "//div[@id='vendedor']"))).click()
        self.driver.execute_script("window.scrollTo(0, window.innerHeight);")
        time.sleep(0.5)
        WebDriverWait(self.driver, 25).until(
            EC.element_to_be_clickable((By.XPATH, "//p[normalize-space()='Concesionario autorizados']"))).click()
        WebDriverWait(self.driver, 25).until(EC.element_to_be_clickable((By.XPATH, "//div[@class='footer']"))).click()
        time.sleep(3)
        WebDriverWait(self.driver, 25).until(EC.element_to_be_clickable((((By.XPATH, "//button[@class='dav-button"
                                                                                     "--secondary']"))))).click()


        time.sleep(2000)
